In [43]:
import numpy as np
import tensorflow as tf
import commpy as cp
import scipy.signal as sig
import matplotlib.pyplot as plt
import pandas as pd

%matplotlib inline

In [49]:
channel_size = 1
learning_rate = 0.001
# number of units in hidden layer
num_hidden_units = 10

# Lets start by working with the fft of our channel being real. 
training_inputs = np.random.rand(1000,channel_size)
training_outputs = training_inputs

# Validation inputs
validation_inputs = np.random.rand(1000,channel_size)
validation_outputs = validation_inputs

In [62]:
# placeholder for inputs and outputs
seed = 128
tf_inputs = tf.placeholder(tf.float32, shape=[None, channel_size])
tf_outputs = tf.placeholder(tf.float32, shape=[None, channel_size])

# initialize weights to be random
weights = {
    'hidden1': tf.Variable(tf.random_normal([channel_size, num_hidden_units], seed=seed)),
    'hidden2': tf.Variable(tf.random_normal([num_hidden_units, num_hidden_units], seed=seed)),
    'hidden3': tf.Variable(tf.random_normal([num_hidden_units, num_hidden_units], seed=seed)),
    'output': tf.Variable(tf.random_normal([num_hidden_units, channel_size], seed=seed))
}

# initialize biases to be random
biases = {
    'hidden1': tf.Variable(tf.random_normal([num_hidden_units], seed=seed)),
    'hidden2': tf.Variable(tf.random_normal([num_hidden_units], seed=seed)),
    'hidden3': tf.Variable(tf.random_normal([num_hidden_units], seed=seed)),
    'output': tf.Variable(tf.random_normal([channel_size]))
}

# create network layers
hidden_layer1 = tf.add(tf.matmul(tf_inputs, weights['hidden1']), biases['hidden1'])
hidden_layer1 = tf.nn.relu(hidden_layer1)
#hidden_layer2 = tf.add(tf.matmul(hidden_layer1, weights['hidden2']), biases['hidden2'])
#hidden_layer2 = tf.nn.relu(hidden_layer2)
#hidden_layer3 = tf.add(tf.matmul(hidden_layer2, weights['hidden3']), biases['hidden3'])
#hidden_layer3 = tf.nn.sigmoid(hidden_layer3)

output_layer = tf.add(tf.matmul(hidden_layer1, weights['output']), biases['output'])
#output_layer = tf.nn.sigmoid(output_layer)

# create cost function
#cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(output_layer, tf_outputs))
cost = tf.reduce_sum(tf.subtract(output_layer,tf_outputs))#tf.nn.l2_loss(tf.subtract(output_layer,tf_outputs))

# optimizer to do gradient descent
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    
    for i in range(100):
        # Lets start by working with the fft of our channel being real. 
        training_inputs = np.random.rand(5000,channel_size)
        training_outputs = training_inputs
        
        sess.run(init)
        _, c = sess.run([optimizer, cost], 
                      feed_dict={tf_inputs: training_inputs, tf_outputs: training_outputs})
        
        print("Cost: ", c)

    # find predictions
    predictions = sess.run(output_layer, feed_dict={tf_inputs: validation_inputs})
    predictions2 = sess.run(output_layer, feed_dict={tf_inputs: training_inputs})


Cost:  30556.1
Cost:  15279.7
Cost:  36353.9
Cost:  17495.8
Cost:  52422.9
Cost:  17589.0
Cost:  100061.0
Cost:  38969.5
Cost:  4854.79
Cost:  28374.2
Cost:  24877.8
Cost:  50981.0
Cost:  27058.3
Cost:  52557.2
Cost:  192.93
Cost:  44237.1
Cost:  28378.8
Cost:  3346.25
Cost:  19331.0
Cost:  60006.3
Cost:  25403.8
Cost:  46364.4
Cost:  32523.5
Cost:  45242.1
Cost:  27569.3
Cost:  16850.6
Cost:  -2409.12
Cost:  -2470.67
Cost:  31208.5
Cost:  42415.0
Cost:  39452.9
Cost:  6756.44
Cost:  2881.48
Cost:  59481.6
Cost:  84628.3
Cost:  36388.1
Cost:  37913.6
Cost:  5010.81
Cost:  22866.8
Cost:  9877.54
Cost:  48265.7
Cost:  32483.1
Cost:  -4172.39
Cost:  14955.9
Cost:  22923.7
Cost:  38649.3
Cost:  5876.75
Cost:  46993.7
Cost:  24145.0
Cost:  -1169.42
Cost:  49654.6
Cost:  6578.78
Cost:  36442.8
Cost:  55645.5
Cost:  16080.9
Cost:  23475.6
Cost:  117842.0
Cost:  31045.5
Cost:  21673.4
Cost:  49253.9
Cost:  13260.4
Cost:  49090.3
Cost:  54439.1
Cost:  39276.5
Cost:  47547.8
Cost:  13069.0
Cost:

In [63]:
# printing predictions 
i = 89
print("Predictions: \n", predictions[i:i+10], '\n')
print("Validation Inputs: \n", validation_inputs[i:i+10], '\n')
print("Validation Desired output\n", validation_outputs[i:i+10], '\n')

print("Predictions: \n", predictions2[i:i+10], '\n')
print("Training Inputs: \n", training_inputs[i:i+10], '\n')
print("Training Desired output\n", training_outputs[i:i+10], '\n')

Predictions: 
 [[ 3.87867188]
 [ 3.47505307]
 [ 3.89553142]
 [ 4.74938345]
 [ 5.06337166]
 [ 3.23114347]
 [ 2.73406529]
 [ 3.72823596]
 [ 2.82293677]
 [ 5.21777582]] 

Validation Inputs: 
 [[ 0.47024785]
 [ 0.32819603]
 [ 0.47618158]
 [ 0.77669087]
 [ 0.88719759]
 [ 0.24235309]
 [ 0.06740866]
 [ 0.41730258]
 [ 0.09868659]
 [ 0.94153946]] 

Validation Desired output
 [[ 0.47024785]
 [ 0.32819603]
 [ 0.47618158]
 [ 0.77669087]
 [ 0.88719759]
 [ 0.24235309]
 [ 0.06740866]
 [ 0.41730258]
 [ 0.09868659]
 [ 0.94153946]] 

Predictions: 
 [[ 3.00878644]
 [ 2.98254204]
 [ 2.92164159]
 [ 3.69230676]
 [ 3.25115538]
 [ 3.25847697]
 [ 4.15027714]
 [ 4.79872131]
 [ 2.6231184 ]
 [ 3.54049897]] 

Training Inputs: 
 [[ 0.16409555]
 [ 0.15485893]
 [ 0.13342536]
 [ 0.40465756]
 [ 0.24939623]
 [ 0.25197301]
 [ 0.56583798]
 [ 0.79405506]
 [ 0.02836134]
 [ 0.35122943]] 

Training Desired output
 [[ 0.16409555]
 [ 0.15485893]
 [ 0.13342536]
 [ 0.40465756]
 [ 0.24939623]
 [ 0.25197301]
 [ 0.56583798]
 [ 0.794