In [1]:
import numpy as np
import tensorflow as tf
import commpy as cp
import scipy.signal as sig
import matplotlib.pyplot as plt
import pandas as pd

%matplotlib inline

In [2]:
channel_size = 1
learning_rate = 0.001
# number of units in hidden layer
num_hidden_units = 10

# Lets start by working with the fft of our channel being real. 
training_inputs = np.random.rand(1000,channel_size)
training_outputs = 1/training_inputs

# Validation inputs
validation_inputs = np.random.rand(1000,channel_size)
validation_outputs = 1/validation_inputs

In [9]:
# placeholder for inputs and outputs
seed = 128
tf_inputs = tf.placeholder(tf.float32, shape=[None, channel_size])
tf_outputs = tf.placeholder(tf.float32, shape=[None, channel_size])

# initialize weights to be random
weights = {
    'hidden1': tf.Variable(tf.random_normal([channel_size, num_hidden_units], seed=seed)),
    'hidden2': tf.Variable(tf.random_normal([num_hidden_units, num_hidden_units], seed=seed)),
    'hidden3': tf.Variable(tf.random_normal([num_hidden_units, num_hidden_units], seed=seed)),
    'output': tf.Variable(tf.random_normal([num_hidden_units, channel_size], seed=seed))
}

# initialize biases to be random
biases = {
    'hidden1': tf.Variable(tf.random_normal([num_hidden_units], seed=seed)),
    'hidden2': tf.Variable(tf.random_normal([num_hidden_units], seed=seed)),
    'hidden3': tf.Variable(tf.random_normal([num_hidden_units], seed=seed)),
    'output': tf.Variable(tf.random_normal([channel_size]))
}

# create network layers
hidden_layer1 = tf.add(tf.matmul(tf_inputs, weights['hidden1']), biases['hidden1'])
hidden_layer1 = tf.nn.sigmoid(hidden_layer1)
#hidden_layer2 = tf.add(tf.matmul(hidden_layer1, weights['hidden2']), biases['hidden2'])
#hidden_layer2 = tf.nn.relu(hidden_layer2)
#hidden_layer3 = tf.add(tf.matmul(hidden_layer2, weights['hidden3']), biases['hidden3'])
#hidden_layer3 = tf.nn.sigmoid(hidden_layer3)

output_layer = tf.add(tf.matmul(hidden_layer1, weights['output']), biases['output'])
#output_layer = tf.nn.sigmoid(output_layer)

# create cost function
#cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(output_layer, tf_outputs))
cost = tf.nn.l2_loss(tf.subtract(output_layer,tf_outputs))#tf.nn.l2_loss(tf.subtract(output_layer,tf_outputs))

# optimizer to do gradient descent
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    
    for i in range(100):
        # Lets start by working with the fft of our channel being real. 
        training_inputs = np.random.rand(5000,channel_size)
        training_outputs = training_inputs
        
        sess.run(init)
        _, c = sess.run([optimizer, cost], 
                      feed_dict={tf_inputs: training_inputs, tf_outputs: training_outputs})
        
        print("Cost: ", c)

    # find predictions
    predictions = sess.run(output_layer, feed_dict={tf_inputs: validation_inputs})
    predictions2 = sess.run(output_layer, feed_dict={tf_inputs: training_inputs})


Cost:  29030.8
Cost:  7740.75
Cost:  2895.16
Cost:  3445.93
Cost:  38436.8
Cost:  10273.6
Cost:  60551.9
Cost:  39770.1
Cost:  10844.9
Cost:  5336.07
Cost:  80.7139
Cost:  50235.6
Cost:  16318.7
Cost:  49700.5
Cost:  1636.13
Cost:  4396.52
Cost:  24942.0
Cost:  1636.58
Cost:  58369.7
Cost:  35817.7
Cost:  13114.3
Cost:  18399.5
Cost:  19359.1
Cost:  21253.3
Cost:  13982.4
Cost:  14879.6
Cost:  3371.82
Cost:  7361.91
Cost:  15254.6
Cost:  10695.7
Cost:  14848.9
Cost:  486.306
Cost:  4241.79
Cost:  108843.0
Cost:  74904.0
Cost:  8889.69
Cost:  9050.37
Cost:  2537.75
Cost:  3128.29
Cost:  67.0905
Cost:  16963.4
Cost:  3709.94
Cost:  36.1246
Cost:  1009.47
Cost:  4924.98
Cost:  30380.3
Cost:  1004.23
Cost:  35256.8
Cost:  10.7777
Cost:  10153.5
Cost:  23146.4
Cost:  984.616
Cost:  7143.98
Cost:  64737.4
Cost:  11.2476
Cost:  1881.35
Cost:  83398.5
Cost:  7493.85
Cost:  4988.16
Cost:  64885.0
Cost:  3239.54
Cost:  53399.0
Cost:  40889.4
Cost:  28779.2
Cost:  773.51
Cost:  2098.66
Cost:  787

In [10]:
# printing predictions 
i = 89
print("Predictions: \n", predictions[i:i+10], '\n')
print("Validation Inputs: \n", validation_inputs[i:i+10], '\n')
print("Validation Desired output\n", validation_outputs[i:i+10], '\n')

print("Predictions: \n", predictions2[i:i+10], '\n')
print("Training Inputs: \n", training_inputs[i:i+10], '\n')
print("Training Desired output\n", training_outputs[i:i+10], '\n')

Predictions: 
 [[ 1.6314013 ]
 [ 1.27220225]
 [ 1.35833073]
 [ 1.22237992]
 [ 1.01001883]
 [ 1.64898014]
 [ 1.32956684]
 [ 1.16869497]
 [ 1.22984767]
 [ 1.31091976]] 

Validation Inputs: 
 [[ 0.96113504]
 [ 0.43817204]
 [ 0.55218272]
 [ 0.37483015]
 [ 0.12284163]
 [ 0.99052075]
 [ 0.51343517]
 [ 0.30851794]
 [ 0.38421056]
 [ 0.48868319]] 

Validation Desired output
 [[ 1.04043652]
 [ 2.28220862]
 [ 1.81099474]
 [ 2.667875  ]
 [ 8.14056302]
 [ 1.00956996]
 [ 1.94766555]
 [ 3.24130263]
 [ 2.60273953]
 [ 2.04631553]] 

Predictions: 
 [[ 1.10962701]
 [ 1.54619598]
 [ 1.37286925]
 [ 1.26267552]
 [ 1.62977886]
 [ 1.34413791]
 [ 1.26614857]
 [ 1.17535257]
 [ 1.03457487]
 [ 1.01880109]] 

Training Inputs: 
 [[ 0.23769774]
 [ 0.82452721]
 [ 0.57203762]
 [ 0.42591946]
 [ 0.95844464]
 [ 0.53297617]
 [ 0.43037841]
 [ 0.31663728]
 [ 0.15065854]
 [ 0.13275437]] 

Training Desired output
 [[ 0.23769774]
 [ 0.82452721]
 [ 0.57203762]
 [ 0.42591946]
 [ 0.95844464]
 [ 0.53297617]
 [ 0.43037841]
 [ 0.316