In [1]:
import numpy as np
import commpy as cp
import scipy.signal as sig
import scipy.linalg as la
import math
import matplotlib.pyplot as plt
%matplotlib inline

def channel(input_data_constellations, channel_function):
    """  2. Convolves modulated data with a randomly generated channel fcn of t taps  """
    channel_output = sig.convolve(input_data_constellations, channel_function, mode='full') # convolve input complex data with the channel transfer function
    return channel_output

def gen_matrix(signal, pre_chan_sig_len, L):
    
    order = 2*L+1
    A = []
    signal = np.pad(signal.flatten(), L, 'constant', constant_values=(0))
    for i in range(pre_chan_sig_len):
        A += [np.flip(signal[i: i+order],0)]
    return np.array(A)
def gen_toeplitz(received_signal, channel_length, equalizer_length):
    # offset_amount needs to be same as in "test ()"
    offset_amount = (equalizer_length+1) // 2
    row = np.hstack((received_signal[:offset_amount], np.zeros(equalizer_length-offset_amount)))
    # handle edge case
    if -channel_length+offset_amount >= 0:
        offset_amount2 = len(received_signal)
    else:
        offset_amount2 = -channel_length+offset_amount
    col = received_signal[offset_amount:offset_amount2]
    col = np.hstack((col, np.zeros(len(received_signal)-channel_length+1-len(col))))
    toeplitz = la.toeplitz(col,row)
    return toeplitz
chan = channel(np.array(range(1,21)), [0,0,0,0,1])
print(len(chan), chan)
print(gen_matrix(chan, 20, 10)) #order = 2L+1
print(np.array(gen_toeplitz(chan, 5, 21), dtype=np.int))

(24, array([ 0,  0,  0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 16, 17, 18, 19, 20]))
[[ 7  6  5  4  3  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 8  7  6  5  4  3  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 9  8  7  6  5  4  3  2  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [10  9  8  7  6  5  4  3  2  1  0  0  0  0  0  0  0  0  0  0  0]
 [11 10  9  8  7  6  5  4  3  2  1  0  0  0  0  0  0  0  0  0  0]
 [12 11 10  9  8  7  6  5  4  3  2  1  0  0  0  0  0  0  0  0  0]
 [13 12 11 10  9  8  7  6  5  4  3  2  1  0  0  0  0  0  0  0  0]
 [14 13 12 11 10  9  8  7  6  5  4  3  2  1  0  0  0  0  0  0  0]
 [15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0  0  0  0  0  0]
 [16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0  0  0  0  0]
 [17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0  0  0  0]
 [18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0  0  0]
 [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0  0]
 [20 19 18 17 16 15 14 13